### ISSUE TITLE
Rendering issue using sitegen-maven-plugin

### ISSUE THREAD

**Issue by ghillert** [oracle/helidon-build-tools#343]
The Coherence project is using the `sitegen-maven-plugin` and Coherence's sub-projects are also moving towards using the Helidon-themed `sitegen-maven-plugin`. Coherence `20.12` has been using version `2.0.0-RC1` of the plugin and it works fine for our purposes.

However, versions `2.0.0` to `2.1.2` are causing issues. I have the following `sitegen.yaml` file that works with `2.0.0-RC1`.

```
engine:
  asciidoctor:
    images-dir: "images"
    libraries:
      - "asciidoctor-diagram"
    attributes:
      source-highlighter: "highlight.js"
      highlightjs-theme: "idea"
      plantumlconfig: "_plantuml-config.txt"
      coherence-maven-group-id: "${coherence.group.id}"
      javadoc-root: "https://coherence.community/${revision}/api/java/"
      version-coherence-maven: "${revision}"
      version-coherence-spring: "${project.version}"
      version-commercial-docs: "14.1.1.0"
      version-helidon: "${helidon.version}"
assets:
  - target: "/"
    includes:
      - "css/*.css"
  - target: "/"
    includes:
      - "images/**/*"
header:
  favicon:
    path: "images/logo.png"
    type: "png"
  stylesheets:
    - path: "css/styles.css"
pages:
    - includes:
        - "**/*.adoc"
      excludes:
        - "examples/guides/README.adoc"
        - "examples/tutorials/README.adoc"
backend:
    name: "vuetify"
    homePage: "about/01_overview.adoc"
    releases:
        - "${project.version}"
    navigation:
      title: "Oracle Coherence Spring"
      glyph:
        type: "image"
        value: "images/logo.png"
      items:
        - title: "Project Website"
          pathprefix: "/about"
          items:
            - title: "Components"
              pathprefix: "/about"
              glyph:
                type: "icon"
                value: "assistant"
              items:
                - includes:
                    - "about/*.adoc"
        - title: "Reference Documentation"
          items:
            - title: "HTML"
              glyph:
                type: "icon"
                value: "fa-html5"
              href: "https://tbd"
            - title: "Single Page"
              glyph:
                type: "icon"
                value: "fa-html5"
              href: "https://tbd"
            - title: "PDF"
              glyph:
                type: "icon"
                value: "picture_as_pdf"
              href: "https://tbd"
        - title: "Additional Resources"
          items:
            - title: "Slack"
              glyph:
                type: "icon"
                value: "fa-slack"
              href: "https://join.slack.com/t/oraclecoherence/shared_invite/enQtNzcxNTQwMTAzNjE4LTJkZWI5ZDkzNGEzOTllZDgwZDU3NGM2YjY5YWYwMzM3ODdkNTU2NmNmNDFhOWIxMDZlNjg2MzE3NmMxZWMxMWE"
            - title: "Coherence Web Site"
              glyph:
                type: "icon"
                value: "fa-globe"
              href: "https://coherence.community/"
            - title: "GitHub"
              glyph:
                type: "icon"
                value: "fa-github-square"
              href: "https://github.com/coherence-community/coherence-spring"
```

Using the latest release version `2.1.2` compiles but causes the following browser stacktrace in Chrome:

```
vue.js:584 [Vue warn]: Error in created hook: "TypeError: Cannot read property 'groups' of undefined"

found in

---> <DocNav>
       <VApp>
         <DefaultView>
           <MainView>
             <Root>
warn @ vue.js:584
logError @ vue.js:1715
globalHandleError @ vue.js:1710
handleError @ vue.js:1699
callHook @ vue.js:2897
Vue._init @ vue.js:4547
VueComponent @ vue.js:4715
createComponentInstanceForVnode @ vue.js:4236
init @ vue.js:4053
createComponent @ vue.js:5499
createElm @ vue.js:5447
createChildren @ vue.js:5573
createElm @ vue.js:5475
createChildren @ vue.js:5573
createElm @ vue.js:5475
patch @ vue.js:5982
Vue._update @ vue.js:2637
updateComponent @ vue.js:2765
get @ vue.js:3113
Watcher @ vue.js:3102
mountComponent @ vue.js:2772
Vue$3.$mount @ vue.js:8416
Vue$3.$mount @ vue.js:10777
init @ vue.js:4059
createComponent @ vue.js:5499
createElm @ vue.js:5447
patch @ vue.js:5982
Vue._update @ vue.js:2637
updateComponent @ vue.js:2765
get @ vue.js:3113
Watcher @ vue.js:3102
mountComponent @ vue.js:2772
Vue$3.$mount @ vue.js:8416
Vue$3.$mount @ vue.js:10777
init @ vue.js:4059
createComponent @ vue.js:5499
createElm @ vue.js:5447
patch @ vue.js:6021
Vue._update @ vue.js:2647
updateComponent @ vue.js:2765
get @ vue.js:3113
run @ vue.js:3190
flushSchedulerQueue @ vue.js:2954
(anonymous) @ vue.js:1815
flushCallbacks @ vue.js:1736
Promise.then (async)
microTimerFunc @ vue.js:1784
nextTick @ vue.js:1828
queueWatcher @ vue.js:3041
update @ vue.js:3180
notify @ vue.js:690
reactiveSetter @ vue.js:1015
(anonymous) @ vue-router.js:2514
(anonymous) @ vue-router.js:2513
updateRoute @ vue-router.js:2003
(anonymous) @ vue-router.js:1881
(anonymous) @ vue-router.js:1990
step @ vue-router.js:1720
step @ vue-router.js:1727
runQueue @ vue-router.js:1731
(anonymous) @ vue-router.js:1985
step @ vue-router.js:1720
(anonymous) @ vue-router.js:1724
(anonymous) @ vue-router.js:1970
(anonymous) @ vue-router.js:1763
(anonymous) @ vue-router.js:1839
Promise.then (async)
(anonymous) @ vue-router.js:1786
(anonymous) @ vue-router.js:1807
(anonymous) @ vue-router.js:1807
flatMapComponents @ vue-router.js:1806
(anonymous) @ vue-router.js:1742
iterator @ vue-router.js:1949
step @ vue-router.js:1723
step @ vue-router.js:1727
runQueue @ vue-router.js:1731
confirmTransition @ vue-router.js:1978
transitionTo @ vue-router.js:1880
init @ vue-router.js:2505
beforeCreate @ vue-router.js:546
callHook @ vue.js:2895
Vue._init @ vue.js:4543
Vue$3 @ vue.js:4646
main @ app.js:84
(anonymous) @ (index):62
Show 15 more frames
vue.js:1719 TypeError: Cannot read property 'groups' of undefined
    at VueComponent.created (docNav.js:232)
    at callHook (vue.js:2895)
    at VueComponent.Vue._init (vue.js:4547)
    at new VueComponent (vue.js:4715)
    at createComponentInstanceForVnode (vue.js:4236)
    at init (vue.js:4053)
    at createComponent (vue.js:5499)
    at createElm (vue.js:5447)
    at createChildren (vue.js:5573)
    at createElm (vue.js:5475)
```

For some strange reasons, the latest version requires a `pathprefix` under `- title: "Reference Documentation"` e.g.:
`pathprefix: "/fooooo"` (All sub-items are HTTP-links thus the pathprefix is not used at all). This compiles and runs BUT it produces duplicated green icons:

![image](https://user-images.githubusercontent.com/685363/106659441-d3c3bf00-6542-11eb-9eea-36dc7a0a6e73.png)

It is also interesting to note that the last block `title: "- Additional Resources"` works without a `pathprefix` and does not causes any stacktraces.
